---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.context }}-service
  
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.global.domain | quote }}
    http:
      paths:
      - path: /service
        backend:
          serviceName: {{ .Values.global.pep }}
          servicePort: {{ .Values.global.proxyServicePort }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.context }}-resources
  
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.global.domain | quote }}
    http:
      paths:
      - path: /res
        backend:
          serviceName: {{ .Values.global.pep }}
          servicePort: {{ .Values.global.resourcesServicePort }}
