language: python
python: 3.6.9
jobs:
  include:
    - stage: Testing
      install: pip install -r src/requirements.txt
      install: pip3 install ./
      script: python3 -m unittest src/test/test.py
env:
  DOCKER_COMPOSE_VERSION: 1.25.4
services:
  - docker

jobs:
  include:
    - stage: container creation and publishing
      install: skip
      script: travis/containerCreation.sh um-pep-engine

    - stage: smoke and acceptance test
      install: skip # without this there's a `git clone` executed!
      script: travis/acceptanceTest.sh um-pep-engine 8080 8080 # Service name + external port + internal port for docker

    - stage: release
      if: branch = master AND NOT type IN (pull_request)
      install: skip
      script: travis/release.sh um-pep-engine

import:
  - docs/.travis.yml

notifications:
  slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
#  email:
#    recipients:
#      - a.person@acme.com
#      - a.n.other@acme.com
  on_success: change
  on_failure: always
