version: "3.5"
services:
  um-pep-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: eoepca/um-pep-engine:build
    container_name: um-pep-engine
    networks:
      - eoepca_network
    ports:
      - '5566:5566'
    volumes:
      - ./src/config:/config

  mongo:
    image: 'mongo'
    container_name: 'mongo'
    networks:
      - eoepca_network
    ports:
      - '27017-27019:27017-27019'

networks:
  eoepca_network:
    driver: bridge
    name: eoepcanetwork
