version: 1
disable_existing_loggers: true

formatters:
  verbose:
    format: '%(asctime)s:%(levelname)s:%(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: verbose
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    filename: ../../logs/auth_proxy_server.log
    formatter: verbose
    level: DEBUG
    maxBytes: 1073741824   ## 1 GB log file size before rotation
    backupCount: 10        ## Saves 10 most recent log files

loggers:
  AUTH_PROXY_SERVER:
    level: DEBUG
    handlers: [ console, file ]
    qualname: AUTH_PROXY_SERVER
    propagate: false
