apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.pep }}-cm
data:
  PEP_REALM: {{ .Values.global.realm | quote }}
  PEP_AUTH_SERVER_URL: https://{{ .Values.global.domain }}
  PEP_TOKEN_URL: https://{{ .Values.global.tokenUrl }}
  PEP_PROXY_HOST: {{ .Values.global.serviceHost | quote }}
  PEP_SERVICE_PORT: {{ .Values.global.proxyServicePort | quote }}
  PEP_RESPONSE_PERMISSIONS_LIMIT: {{ .Values.configMap.margin | quote }}
  PEP_RESOURCE_SERVER_ENDPOINT: {{ .Values.configMap.resourceServer | quote }}
  PEP_PDP_POLICY_ENDPOINT: {{ .Values.configMap.pdpPolicy | quote }}
  PEP_VERIFY_SIGNATURE: {{ .Values.configMap.verifySignature | quote }}
  PEP_PROXY_PORT: {{ .Values.global.proxyServicePort | quote }}
  PEP_RESOURCES_SERVICE_PORT: {{ .Values.global.resourcesServicePort | quote }}
  PEP_DEFAULT_RESOURCE_PATH: {{ .Values.configMap.defaultResourcePath | quote }}
  PEP_WORKING_MODE: {{ .Values.configMap.workingMode | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-resources  
data:
  {{ if .Files.Get "scripts/default-resources.json" }}
  default-resources.json: {{ .Files.Get "scripts/default-resources.json" | quote  }}
  {{ else }}
  {{ fail "you need to supply a default resource JSON file! add 'default-resources.json' to your chart 'scripts' directory." }}
  {{ end }}
